language: python

python:
  - "3.5"
  - "2.7"
env:
  - EXAMPLE="MTBLS1"                               EXAMPLE_TYPE=MTBLS  SLUG=MTBLS1
  - EXAMPLE="IPB_HopExample/nmrMLs"                EXAMPLE_TYPE=NMRML  SLUG=IPBHV1
  - EXAMPLE="IPB_HopExample/nmrMLs.v2"             EXAMPLE_TYPE=NMRML  SLUG=IPBHV2
  - EXAMPLE="jcamp-dx_GABA_withoutFID"             EXAMPLE_TYPE=NMRML  SLUG=JCAMPDX
  - EXAMPLE="quantification_example"               EXAMPLE_TYPE=NMRML  SLUG=QUANTEX
  - EXAMPLE="reference_spectra_examples/bmrb"      EXAMPLE_TYPE=NMRML  SLUG=SPECR1
  - EXAMPLE="reference_spectra_examples/hmdb"      EXAMPLE_TYPE=NMRML  SLUG=SPECR2
  - EXAMPLE="reference_spectra_examples/metabohub" EXAMPLE_TYPE=NMRML  SLUG=SPECR3

matrix:
  allow_failures:
      # need to fix the starmap stuff
    - python: "2.7"

      # FAM013_AHTM.PROTON_04.nmrML is not valid XML
    - env: EXAMPLE="IPB_HopExample/nmrMLs"                EXAMPLE_TYPE=NMRML  SLUG=IPBHV1

      # bmse000325.nmrML is not valid XML
    - env: EXAMPLE="reference_spectra_examples/bmrb"      EXAMPLE_TYPE=NMRML  SLUG=SPECR1

  fast_finish: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y default-jre
  - if [ $EXAMPLE_TYPE = "MTBLS" ]; then sudo apt-get install -y curlftpfs; fi

install:
  - pip install -r requirements-py2.txt
  - pip install .

before_script:
  - >
    if [ $EXAMPLE_TYPE = "NMRML" ]; then
    git clone https://github.com/nmrML/nmrML --depth 1;
    else mkdir example_files;
    curlftpfs ftp.ebi.ac.uk/pub/databases/metabolights/studies/public example_files;
    fi
  - wget https://github.com/ISA-tools/ISAvalidator-ISAconverter-BIImanager/releases/download/1.6.5/ISA-validator-1.6.5.zip
  - unzip ISA-validator-1.6.5.zip
  - wget ftp://ftp.ebi.ac.uk/pub/databases/metabolights/submissionTool/ISAcreatorMetaboLights.zip
  - unzip ISAcreatorMetaboLights.zip
  - mkdir out_folder


script:
  - >
    if [ $EXAMPLE_TYPE = "MTBLS" ]; then
    nmrml2isa -i example_files/$EXAMPLE -o out_folder -s $SLUG;
    else nmrml2isa -i nmrML/examples/$EXAMPLE -o out_folder -s $SLUG;
    fi
  - >
    java -cp ISA-validator-1.6.5/isatools_deps.jar
    org.isatools.isatab.manager.SimpleManager validate out_folder/$SLUG
    Configurations/MetaboLightsConfig20140506/


notifications:
  email:
    - althonosdev@gmail.com
